In [2]:
import numpy as np
import pandas as pd


In [72]:
# df = pd.read_csv("/Users/rio/Downloads/simple_loan.csv")
df = pd.read_csv("/Users/rio/Documents/data_science/datasets_for_analysis/csv/simple_loan.csv")

In [8]:
X = df.drop(['target'], axis=1)
X

age  employed own_house     credit
0    young     False         n       fair
1    young     False         n       good
2    young      True         n       good
3    young      True         y       fair
4    young     False         n       fair
5   middle     False         n       fair
6   middle     False         n       good
7   middle      True         y       good
8   middle     False         y  excellent
9   middle     False         y  excellent
10     old     False         y  excellent
11     old     False         y       good
12     old      True         n       good
13     old      True         n  excellent
14     old     False         n       fair
15     old     False         n  excellent
16   young      True         y       fair

In [10]:
y = df['target']
y

0      no
1      no
2     yes
3     yes
4      no
5      no
6      no
7     yes
8     yes
9     yes
10    yes
11    yes
12    yes
13    yes
14     no
15    yes
16    yes
Name: target, dtype: object

In [19]:
from sklearn.preprocessing import LabelEncoder
def labelEncode(data,columns):
    for i in columns:
        lb = LabelEncoder().fit_transform(data[i])
        data[i+'_'] = lb

In [20]:
f_cols = ['age', 'employed', 'own_house', 'credit']
labelEncode(X, f_cols)

In [21]:
y_le = LabelEncoder()
y1 = y_le.fit_transform(y)
y1

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [22]:
# f < e < g : fair < ex < good : 0 < 1 < 2
X

age  employed own_house     credit  age_  employed_  own_house_  \
0    young     False         n       fair     2          0           0   
1    young     False         n       good     2          0           0   
2    young      True         n       good     2          1           0   
3    young      True         y       fair     2          1           1   
4    young     False         n       fair     2          0           0   
5   middle     False         n       fair     0          0           0   
6   middle     False         n       good     0          0           0   
7   middle      True         y       good     0          1           1   
8   middle     False         y  excellent     0          0           1   
9   middle     False         y  excellent     0          0           1   
10     old     False         y  excellent     1          0           1   
11     old     False         y       good     1          0           1   
12     old      True         n       good     1          1           0   
13     old      True         n  excellent     1          1           0   
14     old     False         n       fair     1          0           0   
15     old     False         n  excellent     1          0           0   
16   young      True         y       fair     2          1           1   

    credit_  
0         1  
1         2  
2         2  
3         1  
4         1  
5         1  
6         2  
7         2  
8         0  
9         0  
10        0  
11        2  
12        2  
13        0  
14        1  
15        0  
16        1

In [23]:
from sklearn.naive_bayes import CategoricalNB

In [27]:
model = CategoricalNB()
model

CategoricalNB()

In [28]:
X1 = X.drop(columns=f_cols)
X1

age_  employed_  own_house_  credit_
0      2          0           0        1
1      2          0           0        2
2      2          1           0        2
3      2          1           1        1
4      2          0           0        1
5      0          0           0        1
6      0          0           0        2
7      0          1           1        2
8      0          0           1        0
9      0          0           1        0
10     1          0           1        0
11     1          0           1        2
12     1          1           0        2
13     1          1           0        0
14     1          0           0        1
15     1          0           0        0
16     2          1           1        1

In [29]:
model.fit(X1, y1)

CategoricalNB()

In [34]:
# Log base e of (P) == Ln(P)
model.feature_log_prob_

[array([[-1.09861229, -1.5040774 , -0.81093022],
        [-1.25276297, -0.84729786, -1.25276297]]),
 array([[-0.13353139, -2.07944154],
        [-0.77318989, -0.61903921]]),
 array([[-0.13353139, -2.07944154],
        [-0.95551145, -0.48550782]]),
 array([[-2.19722458, -0.58778666, -1.09861229],
        [-0.84729786, -1.54044504, -1.02961942]])]

In [35]:
model.feature_names_in_

array(['age_', 'employed_', 'own_house_', 'credit_'], dtype=object)

In [36]:
model.alpha

1.0

In [40]:
model.score(X1, y1)

1.0

In [47]:
# first array is age : middle, old, young 
#                target : yes, no
#                3 * 2 = 6 = all posible outcome
# second array is employed
# third array is own_house
# last array is credit
model.category_count_

[array([[2., 1., 3.],
        [3., 5., 3.]]),
 array([[6., 0.],
        [5., 6.]]),
 array([[6., 0.],
        [4., 7.]]),
 array([[0., 4., 2.],
        [5., 2., 4.]])]

In [63]:
model.feature_names_in_

array(['age_', 'employed_', 'own_house_', 'credit_'], dtype=object)

In [65]:
X.head()

age  employed own_house credit  age_  employed_  own_house_  credit_
0  young     False         n   fair     2          0           0        1
1  young     False         n   good     2          0           0        2
2  young      True         n   good     2          1           0        2
3  young      True         y   fair     2          1           1        1
4  young     False         n   fair     2          0           0        1

# $$
Log(x) = Log_e(x) \: \text{or} \: Ln(X)
$$

In [66]:
new_input = [
    [0,1,1,1],
    [1,0,0,2]
]
y_prob_pred = model.predict_proba(new_input)
# first col : No( not allowed )
# second col : Yes( not allowed )

y_prob_pred

/Users/rio/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.0721808 , 0.9278192 ],
       [0.53238717, 0.46761283]])

In [55]:
y_new_predict = model.predict(new_input)
n = 1
for i in y_new_predict:
    print( 'Customer', n, '=>: ', y_le.classes_[i])
    n += 1

Customer 1 =>:  yes
Customer 2 =>:  no


/Users/rio/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


In [57]:
y_new_predict

array([1, 0])

In [59]:
y_le.classes_

array(['no', 'yes'], dtype=object)

In [62]:
y_le.classes_[1],  y_le.classes_[0]

('yes', 'no')

# ถ้าอยากคำนวณเองอ่ะ ลองใช้ excel เท่ๆ

In [68]:
# assignment ส่งเป็น .ipynb และส่ง คำตอบใน assignment ด้วยเด้อ
