In [1]:
import pandas as pd
import numpy as np


In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

Fontconfig warning: ignoring UTF-8: not a valid region tag


In [96]:
path = "/Users/rio/Documents/data_science/datasets_for_analysis/csv/playtennis.csv"
df = pd.read_csv(path)

In [4]:
df.head(4)

outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes

In [5]:
X = df.drop('play', axis=1)
y = df.play

In [6]:
X

outlook  temp humidity  windy
0      sunny   hot     high  False
1      sunny   hot     high   True
2   overcast   hot     high  False
3      rainy  mild     high  False
4      rainy  cool   normal  False
5      rainy  cool   normal   True
6   overcast  cool   normal   True
7      sunny  mild     high  False
8      sunny  cool   normal  False
9      rainy  mild   normal  False
10     sunny  mild   normal   True
11  overcast  mild     high   True
12  overcast   hot   normal  False
13     rainy  mild     high   True
14  overcast   hot     high  False
15     rainy  mild     high  False
16     sunny  mild     high  False
17     rainy  cool   normal   True
18     sunny   hot     high  False
19     sunny   hot     high   True

In [54]:
cols = X.columns
cols

Index(['outlook', 'temp', 'humidity', 'windy'], dtype='object')

In [14]:
X.dtypes

outlook     object
temp        object
humidity    object
windy         bool
dtype: object

In [74]:
from sklearn.preprocessing import LabelEncoder

def thisLabelEncode(data,columns):
    for i in columns:
        lb = LabelEncoder().fit_transform(data[i])
        data[i+'_'] = lb
    return data

In [75]:
thisLabelEncode(X, cols).head(3)

outlook temp humidity  windy  outlook_  temp_  humidity_  windy_
0     sunny  hot     high  False         2      1          0       0
1     sunny  hot     high   True         2      1          0       1
2  overcast  hot     high  False         0      1          0       0

In [18]:
# LabelEncoder().fit_transform(X[1])
for i in X.columns:
    # print(i)
    lb = LabelEncoder().fit_transform(X[i])
    print(lb)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1 0 1 2 1 2 2]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2 1 2 2 0 1 1]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 0]
[0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1]


In [25]:
type(X['outlook'])

pandas.core.series.Series

In [30]:
X['outlook'].dtypes

dtype('O')

In [35]:
X['outlook'][:5]

0       sunny
1       sunny
2    overcast
3       rainy
4       rainy
Name: outlook, dtype: object

In [38]:
for ol in X['outlook']:
    print(f"{ol}, ", end=" ")

sunny,  sunny,  overcast,  rainy,  rainy,  rainy,  overcast,  sunny,  sunny,  rainy,  sunny,  overcast,  overcast,  rainy,  overcast,  rainy,  sunny,  rainy,  sunny,  sunny,  

In [45]:
# n = 5
n = 8

encoded = LabelEncoder().fit_transform(X['outlook'][:n])
for i, ol in enumerate(X['outlook'][:n]):
    # print(f"{ol}, ", end="")
    # print(f"{i} : {encoded[i]} {ol}")
    print(f"{encoded[i]} {ol}")

2 sunny
2 sunny
0 overcast
1 rainy
1 rainy
1 rainy
0 overcast
2 sunny


In [ ]:
for i i

In [77]:
X_labeled = thisLabelEncode(X, cols)
X_labeled.head(3)

outlook temp humidity  windy  outlook_  temp_  humidity_  windy_
0     sunny  hot     high  False         2      1          0       0
1     sunny  hot     high   True         2      1          0       1
2  overcast  hot     high  False         0      1          0       0

In [41]:
y.values

array(['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no'],
      dtype=object)

In [46]:
encoder = LabelEncoder()
y_labeled = encoder.fit_transform(y)
y_labeled

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [47]:
LabelEncoder().fit_transform(["a", 'a', 'a', 'b', 'b', 'c'])

array([0, 0, 0, 1, 1, 2])

In [50]:
for i, label in enumerate(y_labeled):
    print(label, y.values[i])

0 no
0 no
1 yes
1 yes
1 yes
0 no
1 yes
0 no
1 yes
1 yes
1 yes
1 yes
1 yes
0 no
1 yes
1 yes
0 no
0 no
0 no
0 no


In [51]:
X

outlook  temp humidity  windy
0      sunny   hot     high  False
1      sunny   hot     high   True
2   overcast   hot     high  False
3      rainy  mild     high  False
4      rainy  cool   normal  False
5      rainy  cool   normal   True
6   overcast  cool   normal   True
7      sunny  mild     high  False
8      sunny  cool   normal  False
9      rainy  mild   normal  False
10     sunny  mild   normal   True
11  overcast  mild     high   True
12  overcast   hot   normal  False
13     rainy  mild     high   True
14  overcast   hot     high  False
15     rainy  mild     high  False
16     sunny  mild     high  False
17     rainy  cool   normal   True
18     sunny   hot     high  False
19     sunny   hot     high   True

In [57]:
cols

Index(['outlook', 'temp', 'humidity', 'windy'], dtype='object')

In [62]:
X.head(2)

outlook temp humidity  windy
0   sunny  hot     high  False
1   sunny  hot     high   True

In [66]:
df.head(2)

outlook temp humidity  windy play
0   sunny  hot     high  False   no
1   sunny  hot     high   True   no

In [79]:
X1 = X_labeled.drop(columns=cols)
X1.head()

outlook_  temp_  humidity_  windy_
0         2      1          0       0
1         2      1          0       1
2         0      1          0       0
3         1      2          0       0
4         1      0          1       0

In [94]:
from sklearn.naive_bayes import CategoricalNB


model = CategoricalNB()
model.fit(X1, y_labeled)

CategoricalNB()

In [95]:
# from sklearn.naive_bayes import 

In [81]:
model.feature_log_prob_

[array([[-2.48490665, -1.09861229, -0.5389965 ],
        [-0.84729786, -1.02961942, -1.54044504]]),
 array([[-1.38629436, -0.87546874, -1.09861229],
        [-1.25276297, -1.25276297, -0.84729786]]),
 array([[-0.31845373, -1.29928298],
        [-0.77318989, -0.61903921]]),
 array([[-0.78845736, -0.6061358 ],
        [-0.36772478, -1.178655  ]])]

In [82]:
model.category_count_

[array([[0., 3., 6.],
        [5., 4., 2.]]),
 array([[2., 4., 3.],
        [3., 3., 5.]]),
 array([[7., 2.],
        [5., 6.]]),
 array([[4., 5.],
        [8., 3.]])]

In [83]:
model.feature_names_in_

array(['outlook_', 'temp_', 'humidity_', 'windy_'], dtype=object)

In [84]:
# X.to_numpy()
# np.unique(X.to_numpy))
# X.drop_duplicates()

In [85]:
X.outlook.unique()

array(['sunny', 'overcast', 'rainy'], dtype=object)

In [86]:
X.outlook_.unique()

array([2, 0, 1])

In [87]:
for col in X.columns[:4]:
    
    print(X[col].unique())
    print(X1[col + "_"].unique())
    print()
    # print(col)

['sunny' 'overcast' 'rainy']
[2 0 1]

['hot' 'mild' 'cool']
[1 2 0]

['high' 'normal']
[0 1]

[False  True]
[0 1]



In [88]:
ol_cols = ['outlook', 'outlook_']
X[ol_cols].drop_duplicates()

outlook  outlook_
0     sunny         2
2  overcast         0
3     rainy         1

In [89]:
cols

Index(['outlook', 'temp', 'humidity', 'windy'], dtype='object')

In [90]:
for col in cols:
    pair_cols = [col, col + "_"]
    print(X[pair_cols].drop_duplicates().to_numpy())
    # X[pair_cols].drop_duplicates()

[['sunny' 2]
 ['overcast' 0]
 ['rainy' 1]]
[['hot' 1]
 ['mild' 2]
 ['cool' 0]]
[['high' 0]
 ['normal' 1]]
[[False 0]
 [True 1]]


In [91]:

ol_cols = ['outlook', 'outlook_']
X[ol_cols].drop_duplicates()

outlook  outlook_
0     sunny         2
2  overcast         0
3     rainy         1

#### example outlook Temp humidity windy play
1. sunny cool normal TRUE ?
2. rainy mild normal FALSE ?

In [92]:
y_to_pred = np.array([
    [2, 0, 1, 1],
    [1, 2, 1, 0]
])

In [93]:
model.predict_proba(y_to_pred)

/Users/rio/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.6363419 , 0.3636581 ],
       [0.16493552, 0.83506448]])

In [125]:
model.predict(y_to_pred)

/Users/rio/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([0, 1])

In [126]:
model.predict_log_proba(y_to_pred)

/Users/rio/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[-0.45201928, -1.01154115],
       [-1.80220068, -0.18024633]])

In [128]:
encoder.classes_

array(['no', 'yes'], dtype=object)

In [130]:
encoder.get_params()

{}

In [142]:
model.predict_proba(y_to_pred)

/Users/rio/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.6363419 , 0.3636581 ],
       [0.16493552, 0.83506448]])

In [139]:
y_new_pred_with_labeled = model.predict(y_to_pred)

for i, result in enumerate(y_new_pred_with_labeled, 1):
    print("With all of Factors %d => %s" %(i, encoder.classes_[i-1] + " Play"))

With all of Factors 1 => no Play
With all of Factors 2 => yes Play


/Users/rio/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(
