In [2]:
path = "/Users/rio/Documents/data_science/datasets_for_analysis/csv/playtennis.csv"

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [4]:
A = ['a', 'a', 'b', 'a', 'c']
A = np.array(A)
OneHotEncoder().fit_transform(A.reshape(-1, 1))

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [5]:
K = OneHotEncoder().fit_transform(A.reshape(-1, 1))
K.data

array([1., 1., 1., 1., 1.])

In [6]:
import pandas as pd

In [77]:
df = pd.read_csv(path)
df.head(3)

outlook temp humidity  windy play
0     sunny  hot     high  False   no
1     sunny  hot     high   True   no
2  overcast  hot     high  False  yes

In [8]:
df.describe()


outlook  temp humidity  windy play
count       20    20       20     20   20
unique       3     3        2      2    2
top      sunny  mild     high  False  yes
freq         8     8       12     12   11

In [9]:
df.dtypes

outlook     object
temp        object
humidity    object
windy         bool
play        object
dtype: object

In [23]:
dummpy_X = df['temp']
dummpy_X.values

array(['hot', 'hot', 'hot', 'mild', 'cool', 'cool', 'cool', 'mild',
       'cool', 'mild', 'mild', 'mild', 'hot', 'mild', 'hot', 'mild',
       'mild', 'cool', 'hot', 'hot'], dtype=object)

In [26]:
lb_enc = LabelEncoder()
lb_enc

LabelEncoder()

In [37]:
l = ['banana', 'banana',' Banana', 'apple']

In [45]:
bb = np.random.choice(['a','b','c'], size=10)
bb

array(['b', 'c', 'a', 'b', 'b', 'a', 'c', 'c', 'a', 'a'], dtype='<U1')

In [50]:
lb_enc.fit(l).transform(l)

array([2, 2, 0, 1])

In [52]:
for i in range(len(bb)):
    print(bb[i], lb_enc.fit_transform(bb)[i])

b 1
c 2
a 0
b 1
b 1
a 0
c 2
c 2
a 0
a 0


In [11]:
lb_encoder = LabelEncoder()
lb_encoder.fit(dummpy_X).transform(dummpy_X)

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 0, 1, 1])

In [57]:
df.head(8)

outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes
5     rainy  cool   normal   True   no
6  overcast  cool   normal   True  yes
7     sunny  mild     high  False   no

In [58]:
df.dtypes

outlook     object
temp        object
humidity    object
windy         bool
play        object
dtype: object

In [76]:
df.columns

AttributeError: 'NoneType' object has no attribute 'columns'

In [100]:
cols = df.columns
# cols
# df.copy().iloc[5,5]
ex_df = df.copy()
# ex_df['temp'][4] = None
# ex_df.loc(5)
ex_df.head(3)

# ex_df

outlook temp humidity  windy play
0     sunny  hot     high  False   no
1     sunny  hot     high   True   no
2  overcast  hot     high  False  yes

In [110]:
cols = df.columns

encoded_df = df.copy().drop(columns=cols)

# type(df[cols[0]])
# for c in cols[:1]:
for c in cols:
    encoded_col = LabelEncoder().fit_transform(df[c])
    # print(encoded_col)
    # encoded_col.reshape(1, -1)
    encoded_col.reshape(-1, 1)
    # print(df[c].values)
    print(encoded_col)
    print()
    

[2 2 0 1 1 1 0 2 2 1 2 0 0 1 0 1 2 1 2 2]

[1 1 1 2 0 0 0 2 0 2 2 2 1 2 1 2 2 0 1 1]

[0 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 0]

[0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1]

[0 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0]



In [12]:
cols = df.columns
encoded_df = df.copy().drop(columns=cols)
for col in cols:
    # print(col)
    new_encoed_col = lb_encoder.fit_transform(df[col])
    encoded_df["_" + col] = new_encoed_col
    
encoded_df.head()

_outlook  _temp  _humidity  _windy  _play
0         2      1          0       0      0
1         2      1          0       1      0
2         0      1          0       0      1
3         1      2          0       0      1
4         1      0          1       0      1

In [13]:
X_encoded = encoded_df.drop(columns='_play')
X_encoded.head(2)

_outlook  _temp  _humidity  _windy
0         2      1          0       0
1         2      1          0       1

In [14]:
y_encoded = encoded_df['_play']
y_encoded.head()

0    0
1    0
2    1
3    1
4    1
Name: _play, dtype: int64

# Naive Bayes Classification

In [111]:
from sklearn.naive_bayes import CategoricalNB 

In [16]:
model = CategoricalNB()
model.fit(X_encoded, y_encoded)

CategoricalNB()

In [17]:
model.alpha

1.0

In [18]:
model.class_count_

array([ 9., 11.])

In [19]:
# encoded_df[cols]
# cols
for col in encoded_df.columns:
    u = encoded_df[col].unique()
    u1 = df[col[1:]].unique()
    print(u)
    print(u1)
    print()

[2 0 1]
['sunny' 'overcast' 'rainy']

[1 2 0]
['hot' 'mild' 'cool']

[0 1]
['high' 'normal']

[0 1]
[False  True]

[0 1]
['no' 'yes']



In [20]:
model.category_count_

[array([[0., 3., 6.],
        [5., 4., 2.]]),
 array([[2., 4., 3.],
        [3., 3., 5.]]),
 array([[7., 2.],
        [5., 6.]]),
 array([[4., 5.],
        [8., 3.]])]

In [21]:
model.feature_log_prob_

[array([[-2.48490665, -1.09861229, -0.5389965 ],
        [-0.84729786, -1.02961942, -1.54044504]]),
 array([[-1.38629436, -0.87546874, -1.09861229],
        [-1.25276297, -1.25276297, -0.84729786]]),
 array([[-0.31845373, -1.29928298],
        [-0.77318989, -0.61903921]]),
 array([[-0.78845736, -0.6061358 ],
        [-0.36772478, -1.178655  ]])]

In [112]:
model.feature_names_in_

array(['_outlook', '_temp', '_humidity', '_windy'], dtype=object)

In [114]:
model

CategoricalNB()

In [160]:
X_encoded.iloc[1]

_outlook     2
_temp        1
_humidity    0
_windy       1
Name: 1, dtype: int64

In [161]:
pred_x = np.array([
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [0, 1, 1, 1],
    # [1, 0, 0, 2]
])

y_pred = model.predict(X=pred_x)
print(y_pred)
print(lb_encoder.classes_[y_pred])
# y_encoded.classes_

[1 1 1]
['yes' 'yes' 'yes']


/Users/rio/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


In [164]:
model.score(X_encoded, y_encoded)

0.85

/Users/rio/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


ValueError: X has 1 features, but CategoricalNB is expecting 4 features as input.