In [1]:
def f(a,b,c,d):
    return (x and y) and (c or d)

In [2]:
import pandas as pd
from itertools import product, permutations


In [3]:
def truth_table(f):
    values = [list(x) + [f(*x) for x in product([True, False])]]

In [4]:
# [x for x in product([True, False], repr=f.func_code.co_argcount)]

In [5]:
list(product([1,0], repeat=2))

[(1, 1), (1, 0), (0, 1), (0, 0)]

In [6]:
list(product(['l', 'm', 'h'], repeat=1))

[('l',), ('m',), ('h',)]

In [7]:
list(product(['l', 'm', 'h'], repeat=3))

[('l', 'l', 'l'),
 ('l', 'l', 'm'),
 ('l', 'l', 'h'),
 ('l', 'm', 'l'),
 ('l', 'm', 'm'),
 ('l', 'm', 'h'),
 ('l', 'h', 'l'),
 ('l', 'h', 'm'),
 ('l', 'h', 'h'),
 ('m', 'l', 'l'),
 ('m', 'l', 'm'),
 ('m', 'l', 'h'),
 ('m', 'm', 'l'),
 ('m', 'm', 'm'),
 ('m', 'm', 'h'),
 ('m', 'h', 'l'),
 ('m', 'h', 'm'),
 ('m', 'h', 'h'),
 ('h', 'l', 'l'),
 ('h', 'l', 'm'),
 ('h', 'l', 'h'),
 ('h', 'm', 'l'),
 ('h', 'm', 'm'),
 ('h', 'm', 'h'),
 ('h', 'h', 'l'),
 ('h', 'h', 'm'),
 ('h', 'h', 'h')]

In [8]:
k_lst = ['l', 'm', 'h']
for v1 in k_lst:
    for v2 in k_lst:
        for v3 in k_lst:
            print([v1, v2, v3])


['l', 'l', 'l']
['l', 'l', 'm']
['l', 'l', 'h']
['l', 'm', 'l']
['l', 'm', 'm']
['l', 'm', 'h']
['l', 'h', 'l']
['l', 'h', 'm']
['l', 'h', 'h']
['m', 'l', 'l']
['m', 'l', 'm']
['m', 'l', 'h']
['m', 'm', 'l']
['m', 'm', 'm']
['m', 'm', 'h']
['m', 'h', 'l']
['m', 'h', 'm']
['m', 'h', 'h']
['h', 'l', 'l']
['h', 'l', 'm']
['h', 'l', 'h']
['h', 'm', 'l']
['h', 'm', 'm']
['h', 'm', 'h']
['h', 'h', 'l']
['h', 'h', 'm']
['h', 'h', 'h']


In [9]:
x_lst = [1, 2 ,3]
x_lst

[1, 2, 3]

In [10]:
lst

NameError: name 'lst' is not defined

In [ ]:
[] + ['a', 'b'] + ['c']

In [ ]:
# [].append(['a', 'b']).append('c')

In [ ]:
# for 
l = []
for x in x_lst:
    # l.append(x**2)
    # l = l + [x**2]
    l += [x**2]
l

In [ ]:
# list comprehension
[x ** 2 for x in x_lst]

In [ ]:
cartesian_product(lst, 1)

In [11]:
def cartesian_product(lst, n):
    if n == 1:
        return [[x] for x in lst]
    
        # return [(x,) for x in lst]
        # return [tuple() for x in lst]
    # return [(x,) + t for t in cartesian_product(lst, n - 1) for x in lst]
    
    l = []
    for x in lst:
    # for x in ['l', 'm', 'h']:
        for t in cartesian_product(lst, n - 1):
        # for t in [['l'], ['m'], ['h']]:
            # l += [['l'] + ['l']]
            # l += [['l', 'l']]
            l += [[x] + t]
    return l
    # return [  [x] + t for t in cartesian_product(lst, n - 1)  for x in ['l', 'm', 'h']]
lst = ['l', 'm', 'h']
# lst
cartesian_product(lst, n=2)

[['l', 'l'],
 ['l', 'm'],
 ['l', 'h'],
 ['m', 'l'],
 ['m', 'm'],
 ['m', 'h'],
 ['h', 'l'],
 ['h', 'm'],
 ['h', 'h']]

In [12]:
cartesian_product(lst, n=3)

[['l', 'l', 'l'],
 ['l', 'l', 'm'],
 ['l', 'l', 'h'],
 ['l', 'm', 'l'],
 ['l', 'm', 'm'],
 ['l', 'm', 'h'],
 ['l', 'h', 'l'],
 ['l', 'h', 'm'],
 ['l', 'h', 'h'],
 ['m', 'l', 'l'],
 ['m', 'l', 'm'],
 ['m', 'l', 'h'],
 ['m', 'm', 'l'],
 ['m', 'm', 'm'],
 ['m', 'm', 'h'],
 ['m', 'h', 'l'],
 ['m', 'h', 'm'],
 ['m', 'h', 'h'],
 ['h', 'l', 'l'],
 ['h', 'l', 'm'],
 ['h', 'l', 'h'],
 ['h', 'm', 'l'],
 ['h', 'm', 'm'],
 ['h', 'm', 'h'],
 ['h', 'h', 'l'],
 ['h', 'h', 'm'],
 ['h', 'h', 'h']]

In [13]:
3**4

81

In [15]:
k = 1
n = 2*k + 1
n

3

In [52]:
import numpy as np

k = 1
n = 2*k + 1

np.random.seed(99)
u_arr = np.random.randint(0, 100, size=[n])
u_arr


In [53]:
u_list = list(u_arr)
u_list

[1, 35, 57]

In [68]:
mid_from_sorted = sorted(u_list)[get_mid_idx(len(u_list))]
mid_from_sorted

35

In [69]:
# cartesian_product(u_list, n=5)
len(cartesian_product(u_list, n=len(u_list)))

27

In [95]:
def getMidFromSortedList(u_list):
    mid_by_sorted_lst = []
    # ran_mid = 0
    for row in cartesian_product(u_list, n=len(u_list)):
        idx = get_mid_idx(n)
        # print("Us : ", row, '\t\t', "S : ", sorted(row), '\t\t', "m = ", sorted(row)[idx])

        m = sorted(row)[idx]
        mid_by_sorted_lst += [m]
        # print(f"us : {row}\t  s : {sorted(row)} m = {row[1]}")
    return mid_by_sorted_lst
    # print(mid_by_sorted_lst[:20])
    # mid_by_sorted_lst

In [102]:
def countMid(arr, mid):
    count_m = 0
    for x in arr:
        # if x == get_mid(arr):
        if x == mid:
            count_m += 1
    # count_m
    return count_m
countMid(mid_by_sorted_lst, get_mid(u_list))

13

In [106]:
# def getProbOfMid(n_count_mid, n_mid_list):
def getProbOfMid(mid_by_sorted_lst, primitive_random_n_list=u_list):
    # return n_count_mid / n_mid_list
    return countMid(mid_by_sorted_lst, get_mid(primitive_random_n_list)) / len(mid_by_sorted_lst)
    

In [107]:
getProbOfMid(mid_by_sorted_lst, u_list)

0.48148148148148145

In [103]:
mid_by_sorted_lst = getMidFromSortedList(u_list)
print(mid_by_sorted_lst)

[1, 1, 1, 1, 35, 35, 1, 35, 57, 1, 35, 35, 35, 35, 35, 35, 35, 57, 1, 35, 57, 35, 35, 57, 57, 57, 57]


In [104]:
len(mid_by_sorted_lst)

27

In [72]:
u_list

[1, 35, 57]

In [73]:
# [row for row in cartesian_product(u_list, n=len(u_list))]

In [74]:
# (5+1)/2

In [75]:
def get_mid(u_list):
    mid_from_sorted = sorted(u_list)[get_mid_idx(len(u_list))]
    return mid_from_sorted
get_mid(u_list)

35

In [78]:
(3+1   )/ 2  - 1

1.0

In [84]:
def get_mid_idx(n):
    return int((n+1) / 2) - 1
mid_idx = get_mid_idx(n)
ran_mid = u_list[mid_idx]
ran_mid

35

In [86]:
u_list

[1, 35, 57]

In [88]:
print(mid_by_sorted_lst)

[1, 1, 1, 1, 35, 35, 1, 35, 57, 1, 35, 35, 35, 35, 35, 35, 35, 57, 1, 35, 57, 35, 35, 57, 57, 57, 57]


In [83]:
# mid_by_sorted_lst
count_m = 0
for x in mid_by_sorted_lst:
    if x == get_mid(u_list):
        count_m += 1
count_m

13

In [49]:
size_list = len(mid_by_sorted_lst)
size_list

3125

In [50]:
count_m / size_list

0.40032

In [27]:
count_m / len(lst)

0.48148148148148145

In [39]:
# 3^4
len(cartesian_product(lst, n=4))

81

In [40]:
# for 

In [41]:
# if n == 1:
#     return [(x,) for x in lst]
# return [(x,) + t for t in cartesian_product(lst, n - 1) for x in lst]

In [42]:
import numpy as np
weight = np.array([2, 5, 10, 5])
# list(product([True, False], repeat=4))
base_list = list(product([1, 0], repeat=4))
base_arr = np.array(base_list)

In [43]:
base_list

[(1, 1, 1, 1),
 (1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 1, 0, 0),
 (1, 0, 1, 1),
 (1, 0, 1, 0),
 (1, 0, 0, 1),
 (1, 0, 0, 0),
 (0, 1, 1, 1),
 (0, 1, 1, 0),
 (0, 1, 0, 1),
 (0, 1, 0, 0),
 (0, 0, 1, 1),
 (0, 0, 1, 0),
 (0, 0, 0, 1),
 (0, 0, 0, 0)]

In [44]:
weight * base_arr


array([[ 2,  5, 10,  5],
       [ 2,  5, 10,  0],
       [ 2,  5,  0,  5],
       [ 2,  5,  0,  0],
       [ 2,  0, 10,  5],
       [ 2,  0, 10,  0],
       [ 2,  0,  0,  5],
       [ 2,  0,  0,  0],
       [ 0,  5, 10,  5],
       [ 0,  5, 10,  0],
       [ 0,  5,  0,  5],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  5],
       [ 0,  0, 10,  0],
       [ 0,  0,  0,  5],
       [ 0,  0,  0,  0]])

In [45]:
allowedWeight = (weight * base_arr)
allowedWeight

array([[ 2,  5, 10,  5],
       [ 2,  5, 10,  0],
       [ 2,  5,  0,  5],
       [ 2,  5,  0,  0],
       [ 2,  0, 10,  5],
       [ 2,  0, 10,  0],
       [ 2,  0,  0,  5],
       [ 2,  0,  0,  0],
       [ 0,  5, 10,  5],
       [ 0,  5, 10,  0],
       [ 0,  5,  0,  5],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  5],
       [ 0,  0, 10,  0],
       [ 0,  0,  0,  5],
       [ 0,  0,  0,  0]])

In [9]:
np.sum(allowedWeight, axis=1)

array([22, 17, 12,  7, 17, 12,  7,  2, 20, 15, 10,  5, 15, 10,  5,  0])

In [10]:
sum_weight_arr = np.sum(allowedWeight, axis=1)
np.argmax(sum_weight_arr)

0

In [11]:
C = 16
(sum_weight_arr <= C) * 1

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [12]:
fancy_idx_pass_16 = (sum_weight_arr <= C) * 1
# allowedWeight[fancy_idx_pass_16]

In [13]:
fancy_idx_pass_16 = (sum_weight_arr <= C)
fancy_idx_pass_16

array([False, False,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True])

In [14]:
df = pd.DataFrame(allowedWeight)
df[fancy_idx_pass_16]

0  1   2  3
2   2  5   0  5
3   2  5   0  0
5   2  0  10  0
6   2  0   0  5
7   2  0   0  0
9   0  5  10  0
10  0  5   0  5
11  0  5   0  0
12  0  0  10  5
13  0  0  10  0
14  0  0   0  5
15  0  0   0  0

In [15]:
# sum weight 
df[fancy_idx_pass_16].sum(axis=1)

2     12
3      7
5     12
6      7
7      2
9     15
10    10
11     5
12    15
13    10
14     5
15     0
dtype: int64

In [32]:
df[fancy_idx_pass_16]
df_2 = df.copy()
df_2['sum_weight'] = df_2.sum(axis=1)
df_2

0  1   2  3  sum_weight
0   2  5  10  5          22
1   2  5  10  0          17
2   2  5   0  5          12
3   2  5   0  0           7
4   2  0  10  5          17
5   2  0  10  0          12
6   2  0   0  5           7
7   2  0   0  0           2
8   0  5  10  5          20
9   0  5  10  0          15
10  0  5   0  5          10
11  0  5   0  0           5
12  0  0  10  5          15
13  0  0  10  0          10
14  0  0   0  5           5
15  0  0   0  0           0

In [33]:
values = np.array([20,30,50,10])
allowedWeight * values

array([[ 40, 150, 500,  50],
       [ 40, 150, 500,   0],
       [ 40, 150,   0,  50],
       [ 40, 150,   0,   0],
       [ 40,   0, 500,  50],
       [ 40,   0, 500,   0],
       [ 40,   0,   0,  50],
       [ 40,   0,   0,   0],
       [  0, 150, 500,  50],
       [  0, 150, 500,   0],
       [  0, 150,   0,  50],
       [  0, 150,   0,   0],
       [  0,   0, 500,  50],
       [  0,   0, 500,   0],
       [  0,   0,   0,  50],
       [  0,   0,   0,   0]])

In [35]:
df_2['sum_value'] = pd.DataFrame(allowedWeight*values).sum(axis=1)
df_2

0  1   2  3  sum_weight  sum_value
0   2  5  10  5          22        740
1   2  5  10  0          17        690
2   2  5   0  5          12        240
3   2  5   0  0           7        190
4   2  0  10  5          17        590
5   2  0  10  0          12        540
6   2  0   0  5           7         90
7   2  0   0  0           2         40
8   0  5  10  5          20        700
9   0  5  10  0          15        650
10  0  5   0  5          10        200
11  0  5   0  0           5        150
12  0  0  10  5          15        550
13  0  0  10  0          10        500
14  0  0   0  5           5         50
15  0  0   0  0           0          0

In [37]:
df_2[df_2["sum_weight"] <= 16]

0  1   2  3  sum_weight  sum_value
2   2  5   0  5          12        240
3   2  5   0  0           7        190
5   2  0  10  0          12        540
6   2  0   0  5           7         90
7   2  0   0  0           2         40
9   0  5  10  0          15        650
10  0  5   0  5          10        200
11  0  5   0  0           5        150
12  0  0  10  5          15        550
13  0  0  10  0          10        500
14  0  0   0  5           5         50
15  0  0   0  0           0          0

In [52]:
value_and_less_than_16_df =  df_2[df_2["sum_weight"] <= 16]['sum_value']
value_and_less_than_16_df

2     240
3     190
5     540
6      90
7      40
9     650
10    200
11    150
12    550
13    500
14     50
15      0
Name: sum_value, dtype: int64

In [53]:
max_value_and_less_than_16_idx = df_2[df_2["sum_weight"] <= 16]['sum_value'].argmax()
max_value_and_less_than_16_idx

5

In [56]:
# df_2.loc(max_value_and_less_than_16_idx)
df_2[df_2["sum_weight"] <= 16].iloc[max_value_and_less_than_16_idx]

0               0
1               5
2              10
3               0
sum_weight     15
sum_value     650
Name: 9, dtype: int64

In [57]:
df_2[df_2['sum_weight'] <= 16]

0  1   2  3  sum_weight  sum_value
2   2  5   0  5          12        240
3   2  5   0  0           7        190
5   2  0  10  0          12        540
6   2  0   0  5           7         90
7   2  0   0  0           2         40
9   0  5  10  0          15        650
10  0  5   0  5          10        200
11  0  5   0  0           5        150
12  0  0  10  5          15        550
13  0  0  10  0          10        500
14  0  0   0  5           5         50
15  0  0   0  0           0          0

In [19]:

df[fancy_idx_pass_16]

0  1   2  3
2   2  5   0  5
3   2  5   0  0
5   2  0  10  0
6   2  0   0  5
7   2  0   0  0
9   0  5  10  0
10  0  5   0  5
11  0  5   0  0
12  0  0  10  5
13  0  0  10  0
14  0  0   0  5
15  0  0   0  0

In [20]:
# df[fancy_idx_pass_16]