In [25]:
import numpy as np
k = """1 4 3 1 2
2 2 1 3 4
3 1 3 4 2
4 4 3 1 2""".split()
k = np.array([int(k) for k in k])
k.reshape(4,-1)

lll = []
# [g for g in k]
[g for g in k.reshape(4,-1)]
# np.argmax(k)


[array([1, 4, 3, 1, 2]),
 array([2, 2, 1, 3, 4]),
 array([3, 1, 3, 4, 2]),
 array([4, 4, 3, 1, 2])]

In [28]:
[list(g) for g in k.reshape(4,-1)]

[[1, 4, 3, 1, 2], [2, 2, 1, 3, 4], [3, 1, 3, 4, 2], [4, 4, 3, 1, 2]]

In [33]:
t = 2
for i in range(t):
    women = []
    men = []
    n = 4
    for j in range(n):
        k = """1 4 3 1 2
        2 2 1 3 4
        3 1 3 4 2
        4 4 3 1 2""".split()
        k = np.array([int(ki) for ki in k])
        # men.append(k.reshape(4,-1)[i])
        o = k.reshape(4,-1)[i]
        men.append(list(o))

    for j in range(n):
        k = """1 3 2 4 1
        2 2 3 1 4
        3 3 1 2 4
        4 3 2 4 1""".split()
        k = np.array([int(ki) for ki in k])
        o = k.reshape(4,-1)[i]
        women.append(list(o))

In [41]:
women

[[2, 2, 3, 1, 4], [2, 2, 3, 1, 4], [2, 2, 3, 1, 4], [2, 2, 3, 1, 4]]

In [42]:
women[0]

[2, 2, 3, 1, 4]

In [40]:
women[0].index(1)

3

In [36]:
men

[[2, 2, 1, 3, 4], [2, 2, 1, 3, 4], [2, 2, 1, 3, 4], [2, 2, 1, 3, 4]]

In [156]:
import numpy as np
def SMP_v2():
    t = 2


    for i in range(t):
        women = []
        men = []
        n = 4
        for j in range(n):
            k = """1 4 3 1 2
            2 2 1 3 4
            3 1 3 4 2
            4 4 3 1 2""".split()
            k = np.array([int(ki) for ki in k])
            # men.append(k.reshape(4,-1)[i])
            o = k.reshape(4,-1)[i]
            # men.append(list(o))
            women.append(list(o))
            
        for j in range(n):
            k = """1 3 2 4 1
            2 2 3 1 4
            3 3 1 2 4
            4 3 2 4 1""".split()
            k = np.array([int(ki) for ki in k])
            o = k.reshape(4,-1)[i]
            men.append(list(o))
            # women.append(list(o))

    wi = [-1]*n
    mi = [1]*n
    while -1 in wi:
        for m0 in range(n):
            # print(men[m0][mi[m0]])
            w0 = men[m0][mi[m0]] - 1
            if(wi[w0] < 0):
                wi[w0] = m0
            else:
                p0 = women[w0][1:].index(wi[w0]+1)
                p1 = women[w0][1:].index(m0+1)

                if p1<p0: # new men
                    # kick old guy
                    mi[wi[w0]] = mi[wi[w0]] + 1
                    wi[w0] = m0
                elif p0<p1: # same man
                    mi[m0] = mi[m0] + 1
        
    for w in range(n):
        print(w+1, wi[w]+1)

    # print()
    # print(women)
    # print(men)
SMP_v2()

1 3
2 2
3 1
4 4


In [109]:
# 7 women, 7 men
womenOrd_with_preference = \
    """1 3 4 2 1 6 7 5
    2 6 4 2 3 5 1 7
    3 6 3 5 7 2 4 1
    4 1 6 3 2 4 7 5
    5 1 6 5 3 4 7 2
    6 1 7 3 4 5 6 2
    7 5 6 2 4 3 7 1"""
v = womenOrd_with_preference.split()
womenOrd_with_preference = [int(wi) 
                           for wi in v]
# womenOrd_with_preference
wo_p = womenOrd_with_preference
# [[every4w] for every4w in wo_p]
# for forth in range()
# list(range(16)) % 4
# "0 1 2 3 " * 2
indexes = list(range(len(wo_p)))
is_multiple_of5 = [(idx+1)%5==0 for idx in indexes]
# idx_every5
big_list = []
# for boolean, val in map(is_multiple_of5, wo_p):
#     # if boolean == True:
#     #     li = val
#     #     big_list += [val]
    # print(boolean, val)

        
    
# wo_p[idx_every5]
    
# wo_p.index(3)
# [x for x in wo_p[]]

In [98]:
len(wo_p), len(is_multiple_of5)

(56, 56)

In [102]:
# enumerate(is_multiple_of5, wo_p)

In [126]:
# womenOrd_with_preference
womenOrd_with_preference_str = \
"""1 3 4 2 1 6 7 5
2 6 4 2 3 5 1 7
3 6 3 5 7 2 4 1
4 1 6 3 2 4 7 5
5 1 6 5 3 4 7 2
6 1 7 3 4 5 6 2
7 5 6 2 4 3 7 1"""
def cleaner(ord_with_pref="", n_row=0):
    k = ord_with_pref.split()
    k = np.array([int(ki) for ki in k])
    women_ord_pref = k.reshape(n_row,-1)
    women_ord_pref = [
        list(row) for row in women_ord_pref
    ]
    return women_ord_pref
cleaner(womenOrd_with_preference_str, 7)

[[1, 3, 4, 2, 1, 6, 7, 5],
 [2, 6, 4, 2, 3, 5, 1, 7],
 [3, 6, 3, 5, 7, 2, 4, 1],
 [4, 1, 6, 3, 2, 4, 7, 5],
 [5, 1, 6, 5, 3, 4, 7, 2],
 [6, 1, 7, 3, 4, 5, 6, 2],
 [7, 5, 6, 2, 4, 3, 7, 1]]

In [165]:
list(cleaner(womenOrd_with_preference_str, 7))

[[1, 3, 4, 2, 1, 6, 7, 5],
 [2, 6, 4, 2, 3, 5, 1, 7],
 [3, 6, 3, 5, 7, 2, 4, 1],
 [4, 1, 6, 3, 2, 4, 7, 5],
 [5, 1, 6, 5, 3, 4, 7, 2],
 [6, 1, 7, 3, 4, 5, 6, 2],
 [7, 5, 6, 2, 4, 3, 7, 1]]

In [166]:
cleaner(womenOrd_with_preference_str, 7)

[[1, 3, 4, 2, 1, 6, 7, 5],
 [2, 6, 4, 2, 3, 5, 1, 7],
 [3, 6, 3, 5, 7, 2, 4, 1],
 [4, 1, 6, 3, 2, 4, 7, 5],
 [5, 1, 6, 5, 3, 4, 7, 2],
 [6, 1, 7, 3, 4, 5, 6, 2],
 [7, 5, 6, 2, 4, 3, 7, 1]]

In [167]:
import numpy as np


def cleaner(ord_with_pref="", n_row=0):
    k = ord_with_pref.split()
    k = np.array([int(ki) for ki in k])
    ord_with_pref = k.reshape(n_row,-1)
    ord_with_pref = [
        list(row) for row in ord_with_pref
    ]
    return ord_with_pref

def SMP_v3(womenOrder_with_herPreference_str,
          menOrder_with_hisPreference_str, n=0):
    t = 1


    for i in range(t):
        women = []
        men = []
        women = cleaner(womenOrder_with_herPreference_str
                       ,n)
        men = cleaner(menOrder_with_hisPreference_str,
                     n)
        

    wi = [-1]*n
    mi = [1]*n
    while -1 in wi:
        for m0 in range(n):
            # print(men[m0][mi[m0]])
            w0 = men[m0][mi[m0]] - 1
            if(wi[w0] < 0):
                wi[w0] = m0
            else:
                p0 = women[w0][1:].index(wi[w0]+1)
                p1 = women[w0][1:].index(m0+1)

                if p1<p0: # new men
                    # kick old guy
                    mi[wi[w0]] = mi[wi[w0]] + 1
                    wi[w0] = m0
                elif p0<p1: # same man
                    mi[m0] = mi[m0] + 1
        
    for w in range(n):
        print(w+1, wi[w]+1)

    # print()
    # print(women)
    # print(men)

In [177]:
womenOrd_with_preference = \
"""1 3 4 2 1 6 7 5
2 6 4 2 3 5 1 7
3 6 3 5 7 2 4 1
4 1 6 3 2 4 7 5
5 1 6 5 3 4 7 2
6 1 7 3 4 5 6 2
7 5 6 2 4 3 7 1"""

menOrd_with_preference = \
"""1 4 5 3 7 2 6 1
2 5 6 4 7 3 2 1
3 1 6 5 4 3 7 2
4 3 5 6 7 2 4 1
5 1 7 6 4 3 5 2
6 6 3 7 5 2 4 1
7 1 7 4 2 6 5 3"""
SMP_v3(womenOrd_with_preference, 
      menOrd_with_preference, n=7)

1 3
2 7
3 4
4 1
5 2
6 6
7 5


In [174]:
def SMP_v1():
    t = int(input())
    # t = 2

    for i in range(t):
        women = []
        men = []
        n = int(input())
        for j in range(n):
            l = input().split()
            men.append([int(i) for i in l])
        for j in range(n):
            l = input().split()
            women.append([int(i) for i in l])

    wi = [-1]*n
    mi = [1]*n
    while -1 in wi:
        for m0 in range(n):
            # print(men[m0][mi[m0]])
            w0 = men[m0][mi[m0]] - 1
            if(wi[w0] < 0):
                wi[w0] = m0
            else:
                p0 = women[w0][1:].index(wi[w0]+1)
                p1 = women[w0][1:].index(m0+1)

                if p1<p0: # new men
                    # kick old guy
                    mi[wi[w0]] = mi[wi[w0]] + 1
                    wi[w0] = m0
                elif p0<p1: # same man
                    mi[m0] = mi[m0] + 1
        for w in range(n):
            print(w+1, wi[w]+1)

    print()
    print(women)
    print(men)


In [175]:
SMP_v1()

 1
 4
 1 3 3 1 2
 2 2 1 3 4
 3 1 3 4 2
 4 4 3 1 2
 1 3 2 4 1 
 2 2 3 1 4
 3 3 1 2 4
 4 3 2 4 1


1 3
2 2
3 1
4 4

[[1, 3, 2, 4, 1], [2, 2, 3, 1, 4], [3, 3, 1, 2, 4], [4, 3, 2, 4, 1]]
[[1, 3, 3, 1, 2], [2, 2, 1, 3, 4], [3, 1, 3, 4, 2], [4, 4, 3, 1, 2]]


In [176]:
[-1]*5

[-1, -1, -1, -1, -1]

In [ ]:
t = int(input())
for i in range(t):
    women = []
    men = []
    n = int(input())
    for j in range(n):
        l = input().split()
        men.append([int(i) for i in l])
    for j in range(n):
        l = input().split()
        women.append([int(i) for i in l])
wi = [-1]*n
mi = [1]*n
while -1 in wi:
    for m0 in range(n):
        # print(men[m0][mi[m0]])
        w0 = men[m0][mi[m0]] - 1
        if(wi[w0] < 0):
            wi[w0] = m0
        else:
            p0 = women[w0][1:].index(wi[w0]+1)
            p1 = women[w0][1:].index(m0+1)

            if p1<p0: # new men
                # kick old guy
                mi[wi[w0]] = mi[wi[w0]] + 1
                wi[w0] = m0
            elif p0<p1: # same man
                mi[m0] = mi[m0] + 1
    for w in range(n):
        print(w+1, wi[w]+1)

# print()
# print(women)
# print(men)