In [2]:
k = 1

n = 2*k + 1
p = [0]*n
# p
n

3

In [3]:
[99] * 3

[99, 99, 99]

In [4]:
[1, 5, 3] * 3

[1, 5, 3, 1, 5, 3, 1, 5, 3]

In [5]:
p

[0, 0, 0]

In [6]:
import numpy as np
np.array([99, 1, 3, 5]) * 3

array([297,   3,   9,  15])

In [94]:
k = 1
n = 2*k + 1
p = [0]*n

# brute force 
# permutation
for i in range(3**n):
    print(f"unsorted = {p}, sorted = {sorted(p)}, mean =   {sorted(p)[1]}")
    # print(p)
    
    # find middle of p // just normal sort
    # by make a copy of p and sorted and pick the kth value
    p[0] += 1
    if p[0] == 3:
        p[0] = 0
        p[1] += 1
    if p[1] == 3:
        p[1] = 0
        p[2] += 1
    if (i+1) % 3 == 0:
        print()
    
    
# p

unsorted = [0, 0, 0], sorted = [0, 0, 0], mean =   0
unsorted = [1, 0, 0], sorted = [0, 0, 1], mean =   0
unsorted = [2, 0, 0], sorted = [0, 0, 2], mean =   0

unsorted = [0, 1, 0], sorted = [0, 0, 1], mean =   0
unsorted = [1, 1, 0], sorted = [0, 1, 1], mean =   1
unsorted = [2, 1, 0], sorted = [0, 1, 2], mean =   1

unsorted = [0, 2, 0], sorted = [0, 0, 2], mean =   0
unsorted = [1, 2, 0], sorted = [0, 1, 2], mean =   1
unsorted = [2, 2, 0], sorted = [0, 2, 2], mean =   2

unsorted = [0, 0, 1], sorted = [0, 0, 1], mean =   0
unsorted = [1, 0, 1], sorted = [0, 1, 1], mean =   1
unsorted = [2, 0, 1], sorted = [0, 1, 2], mean =   1

unsorted = [0, 1, 1], sorted = [0, 1, 1], mean =   1
unsorted = [1, 1, 1], sorted = [1, 1, 1], mean =   1
unsorted = [2, 1, 1], sorted = [1, 1, 2], mean =   1

unsorted = [0, 2, 1], sorted = [0, 1, 2], mean =   1
unsorted = [1, 2, 1], sorted = [1, 1, 2], mean =   1
unsorted = [2, 2, 1], sorted = [1, 2, 2], mean =   2

unsorted = [0, 0, 2], sorted = [0, 0, 2]

In [11]:
def perm(lst):
    if len(lst) == 0: return []
    if len(lst) == 1: return [lst]
    
#   $1 : re-empty list when recurse back to here
    l = []
    for i in range(len(lst)):
        # big list before recursive then $1
        m = lst[i]
        
        remLst = lst[:i] + lst[i+1:]
        # remLst = lst[:i] + lst[i:]
        
        for p in perm(remLst):
            l.append([m] + p)
    return l

In [43]:
# perm([1, 2, 3])
import numpy as np
# perm('123')
perm(list('123'))

[['1', '2', '3'],
 ['1', '3', '2'],
 ['2', '1', '3'],
 ['2', '3', '1'],
 ['3', '1', '2'],
 ['3', '2', '1']]

In [71]:
k = 1
n = 2*k + 1

np.random.seed(1)
np.random.randint(0, 100, size=[10])

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [72]:
n

3

In [84]:
np.random.seed(1)
random_selected = np.random.randint(0, 100, size=[n])
random_selected

array([37, 12, 72])

In [87]:
# perm(random_selected.tolist())

In [88]:
from itertools import permutations

In [89]:
for p in perm(random_selected.tolist()):
    sorted_p = sorted(p)
    # print(p, sorted_p)
    print(p)
    # print(sorted_p)

[37, 12, 72]
[37, 72, 12]
[12, 37, 72]
[12, 72, 37]
[72, 37, 12]
[72, 12, 37]


In [92]:
for p in permutations(random_selected):
    print(p)

(37, 12, 72)
(37, 72, 12)
(12, 37, 72)
(12, 72, 37)
(72, 37, 12)
(72, 12, 37)


In [49]:
list('123')
perm(random_selected.tolist())

[[76, 71, 6], [76, 6, 71], [71, 76, 6], [71, 6, 76], [6, 76, 71], [6, 71, 76]]

In [50]:
perm([4, 5, 6])

[[4, 5, 6], [4, 6, 5], [5, 4, 6], [5, 6, 4], [6, 4, 5], [6, 5, 4]]

In [95]:
0 0 0

SyntaxError: invalid syntax (461907052.py, line 1)

In [96]:
h_arr = np.array([0, 1, 2])
h_arr

array([0, 1, 2])

In [97]:
3*3

9

In [100]:
h_arr.T

array([0, 1, 2])

In [102]:
v_arr = np.array([0,1])
v_arr

array([0, 1])