In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("./BloodPressure.csv")
df

Age  Weight_pounds  Blood_pressure
0    52            173             132
1    59            184             143
2    67            194             153
3    73            211             162
4    64            196             154
5    74            220             168
6    54            188             137
7    61            188             149
8    65            207             159
9    46            167             128
10   72            217             166

In [11]:
X = df[['Age', "Weight_pounds"]].values
X

array([[ 52, 173],
       [ 59, 184],
       [ 67, 194],
       [ 73, 211],
       [ 64, 196],
       [ 74, 220],
       [ 54, 188],
       [ 61, 188],
       [ 65, 207],
       [ 46, 167],
       [ 72, 217]])

In [13]:
y = df['Blood_pressure'].values
y

array([132, 143, 153, 162, 154, 168, 137, 149, 159, 128, 166])

In [14]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [17]:
model.score(X, y)

0.9768471041502091

In [18]:
model.intercept_

30.9941029523483

In [22]:
model.coef_

array([0.86141469, 0.3348592 ])

In [23]:
y_pred = model.predict(X)
y_pred

array([133.71830776, 143.43166173, 153.6715712 , 164.53266567,
       151.75704553, 168.40781313, 140.46402509, 146.49392789,
       156.30191139, 126.54066446, 165.68040616])

In [24]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [26]:
model.score(X, y)

0.9768471041502091

In [27]:
model.score(X, y_pred)

1.0

In [28]:
mean_squared_error(y, y_pred)

3.908438434940735

In [30]:
mean_absolute_error(y, y_pred)

1.6774626489919497

In [33]:
model.predict(X=[
    [57, 
    200]
])

array([147.06657951])