In [1]:
import numpy as np

In [2]:
bin(20)

'0b10100'

In [7]:
[ord(c) for c in "Euro"]


[69, 117, 114, 111]

In [9]:
[bin(ord(c)) for c in "Euro"]

['0b1000101', '0b1110101', '0b1110010', '0b1101111']

In [12]:
(42).bit_length()

6

In [17]:
(42).to_bytes(1, 'little')

b'*'

In [18]:
[c.encode("utf-8") for c in "Euro"]

[b'E', b'u', b'r', b'o']

In [22]:
42 | 42

42

In [24]:
3 ^ 2

1

In [26]:
~3

-4

In [27]:
~156 & 255

99

In [29]:
99 << 1

198

In [30]:
bin(8)

'0b1000'

In [32]:
8 << 1

16

In [33]:
8 >> 1

4

In [34]:
0 >> 1

0

In [48]:
# work in 8 bits data bus -> 1 byte
m = 8
max_mem = 2*m - 1
mem = np.random.randint(0, 8, max_mem)
mem = [bin(data) for data in mem]
mem

['0b110',
 '0b1',
 '0b110',
 '0b111',
 '0b110',
 '0b1',
 '0b100',
 '0b101',
 '0b101',
 '0b1',
 '0b101',
 '0b111',
 '0b100',
 '0b0',
 '0b1']

In [47]:
2**8

256

In [94]:
from tabulate import tabulate

bytes_per_word = 4
table = np.zeros([2**m, bytes_per_word + 1],
                # dtype=str)
                dtype=object)
                # )
cols = ["bs" + str(c) for c in range(bytes_per_word)]
cols.insert(0, "word")
for i in range(2**m):
    byte = i * bytes_per_word
    # print(f"word {i} -> byte {byte}")
    for j in range(bytes_per_word):
        rand = np.random.randint(0, 4)
        # table[i, j + 1] = bin(rand)
        table[i, j + 1] = rand
        
# print(tabulate(table, headers=cols))

In [267]:
# ram chip != ram -> ram chip is smaller unit
class RamChip:
    # size : byte
    def __init__(self, size : int):
        assert size % 2 == 0
        self.size = size
        self.word = (int)(size / 2)
        self.byte_section = (int)(size / 2)
        # self.data = np.zeros(shape=[self.word, self.byte_section])
        self.data = np.random.randint(0, 10,
            [self.word, self.byte_section])
        
    # def __str__(self):
    def __repr__(self):
        # print(f"""size {self.size}
        return f"""size {self.size}
word {self.word}
byte_section {self.byte_section}"""
        
RamChip(2**3)

size 8
word 4
byte_section 4

In [268]:
# class RamSys:
# class MemBoard:
#     def __init__(self, n_ram):
#         # ramChip = RamChip()
#         self.rams = [RamChip(2**3) for n in range(n_ram)]
#     def __repr__(self):
#         return str([rc for rc in self.rams])

# # MemBoard(2)
# MemBoard(2)

In [269]:
class MemBoard:
    def __init__(self, n_data_bus, r_w_each):
        self.chip_per_board = (int)(n_data_bus / r_w_each)
        self.section_select = (int)(n_data_bus / 8)
        self.rams = [RamChip(n_data_bus) for n in range(
            self.chip_per_board
        )]
        # self.sections = np.array([
        #     []
        # ])
        # self.sections = np.array([])
        self.chips_per_sec = self.chip_per_board // self.section_select 
        self.sections = np.empty(
            [self.section_select, self.chips_per_sec],
            dtype=object)
        it_ram = iter(self.rams)
        for i in range(self.section_select):
            for j in range(self.chips_per_sec):
                # self.sections[i][j] = self.rams[k]
                self.sections[i][j] = next(it_ram)
                # k += 1
                
        # self.section_select = (int)(np.log2(r_w_each))
        self.word_select = (int)(np.log2(n_data_bus))
    def __repr__(self):
        ramchips_str = str([rc for rc in self.rams])
        return f"""chip_per_board {self.chip_per_board}
section_select {self.section_select}
word_select {self.word_select}
"""
    def select_word_from_addressing(self, word_sel, sec_sel):
        return self.rams[sec_sel].data[word_sel]
    def print_all(self):
        for i in range(len(self.rams)):
            print("ram chip " + str(i))
            print(self.rams[i].data)
            print("--" * 10)

# MemBoard(2)
# memBoard = MemBoard(32, 1)
# memBoard = MemBoard(2**3, 1)
# memBoard = MemBoard(2**1, 1)
# memBoard = MemBoard(n_data_bus=2**3, r_w_each=4)
# memBoard = MemBoard(n_data_bus=32, r_w_each=4)
# memBoard = MemBoard(, 2)
# print(memBoard.chip_per_board)
# memBoard.__repr__()
# memBoard
# memBoard.print_all()

In [276]:
# data_bus = 2**6 * 2**10 # bits
data_bus = 16 # bits
rw_each = 4 # bits
mmb = MemBoard(data_bus, rw_each)
print(mmb.__repr__())
mmb.print_all()
# mmb.sections
# mmb.section_select

chip_per_board 4
section_select 2
word_select 4

ram chip 0
[[9 1 0 9 9 4 8 3]
 [8 8 1 8 8 3 9 3]
 [1 2 6 6 1 9 0 1]
 [4 0 5 4 6 8 7 7]
 [5 1 5 6 8 7 7 1]
 [1 5 1 4 0 7 3 8]
 [4 1 1 8 7 3 0 0]
 [1 3 9 0 3 1 1 7]]
--------------------
ram chip 1
[[1 8 2 7 3 3 4 2]
 [7 7 9 3 3 2 8 8]
 [7 3 5 6 9 0 0 6]
 [3 0 3 4 8 4 8 5]
 [8 1 7 3 5 7 9 1]
 [7 1 7 9 3 6 3 9]
 [8 9 4 7 4 8 5 2]
 [8 9 3 0 1 8 2 5]]
--------------------
ram chip 2
[[2 8 1 5 4 5 0 8]
 [0 2 9 6 2 6 6 4]
 [2 4 7 4 5 7 3 4]
 [9 0 9 4 8 9 3 2]
 [8 8 6 8 0 4 0 3]
 [6 3 3 3 4 1 1 6]
 [4 9 5 4 5 9 8 6]
 [6 3 4 7 6 4 2 8]]
--------------------
ram chip 3
[[9 1 8 7 1 1 3 3]
 [2 2 4 4 6 1 3 5]
 [0 6 2 5 5 6 3 1]
 [0 8 8 9 2 3 0 8]
 [4 2 4 9 2 5 4 0]
 [0 5 1 8 1 9 8 2]
 [1 3 4 1 6 5 5 8]
 [1 1 0 2 7 8 0 3]]
--------------------


In [280]:
mmb.select_word_from_addressing(0,1)

array([1, 8, 2, 7, 3, 3, 4, 2])

In [292]:
class MemMod:
    def __init__(self, n_data_bus, rw_each, cap_per_chip,
         wanted_mem_size):
        self.wanted_mem_size = wanted_mem_size
        self.chip_per_board = n_data_bus // rw_each
        self.cap_per_board = (self.chip_per_board * cap_per_chip * rw_each) // 8
        self.num_memboard = wanted_mem_size // self.cap_per_board
    def __repr__(self):
        return f"""wanted_mem_size {self.wanted_mem_size}
capacity_per_board {self.wanted_mem_size}
num_memboard {self.num_memboard}
"""
    # def select_word_from_addressing(self, word_sel, sec_sel):
    def select_data_from_addressing(which_board,
                                    word_sel,
                                    sec_sel
                                   ):
        ...

memMod = MemMod(32, 8, 64 * 2**10, (int)(0.5 * 1024*2**10))
# memMod.cap_per_board // 2**10
memMod

wanted_mem_size 524288
capacity_per_board 524288
num_memboard 2