# $$
\text{Statmodels :: proportions_ztest }
$$
## :: Deodorant

In [46]:
from statsmodels.stats.proportion import proportions_ztest
import numpy as np

In [17]:
sig = .05
successes = np.array([320, 300])
samples = np.array([400, 425])


In [18]:
proportions_ztest(
    count=successes, 
    nobs=samples,
                 alternative='two-sided')
# staticmethod def x():
    # print('h')

(3.126437282285804, 0.0017693824065252598)

In [24]:
z, p_val = proportions_ztest(
    count=successes, 
    nobs=samples,
                 alternative='two-sided')

In [27]:
print('z_test : %.5f, p_value : %.5f' % (z, p_val))

z_test : 3.12644, p_value : 0.00177


In [28]:
z

3.126437282285804

In [30]:
# if sig > p_val:
# if p_val < sig:
if sig > p_val:
    print("Reject the null hypothesis")
else:
    print("Accept H_0")
    

Reject the null hypothesis


# $$\text{T-test}$$
## : ttest_ind

In [41]:
sig = .05
# A = np.array([43, 53, 65, 49, 55, 60, 47, 50, 60, 55])
A = np.array([43, 53, 65, 49, 55, 60, 147, 50, 60, 55])
B = np.array([62, 43, 54, 67, 59, 45, 46, 63, 65, 45])

In [42]:
import scipy.stats as stats

In [43]:
# z, p_val = stats.ttest_ind(a=A, b=B, equal_var=True)
z, p_val = stats.ttest_ind(a=A, b=B, equal_var=False)
z, p_val

(0.8866751904733864, 0.39463008299181235)

In [44]:
if sig > p_val:
    s = "Reject H0"
else:
    s = 'Accept H0'
print(s)

Accept H0


# Pretest Posttest : ttest_rel : Paired t-Test

In [47]:
significance = 0.01
group1 = np.array([60, 45, 80, 87, 79, 75, 60, 30, 45])
group2 = np.array([75, 65, 90, 80, 89, 95, 85, 69, 40])

In [50]:
t, p_v = stats.ttest_rel(group1, group2)
p_v, t

(0.018563188104661878, -2.945137866547376)

In [49]:
if sig > p_val:
    s = "Reject H0"
else:
    s = 'Accept H0'
print(s)

Accept H0


# Chisquare

In [51]:
import pandas as pd

In [52]:
df = pd.DataFrame(index=['Marriage', 'Single'],
                 data={'Male': [25, 35],
                      'Female': [15, 25]})
df

Male  Female
Marriage    25      15
Single      35      25

In [53]:
chi2, p, dof, expected = stats.chi2_contingency(
    df, correction=False
)

print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic: 0.17361
p-value: 0.67692
degrees of freedom: 1
expected frequencies:
[[24. 16.]
 [36. 24.]]


In [55]:
row1 = [525,105,50]
row2 = [400,200,25]
row3 = [600,150,10]
data=[row1,row2,row3]
chi2, p, dof, expected = stats.chi2_contingency(data)
print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic: 87.136
p-value: 5.3406e-18
degrees of freedom: 4
expected frequencies:
[[502.17917676 149.83050847  27.99031477]
 [461.56174334 137.71186441  25.72639225]
 [561.2590799  167.45762712  31.28329298]]
